window.ALGORA_CATEGORIES = [
  { id: 'list', name: '线性表', icon: '⇆' },
  { id: 'stack-queue', name: '栈和队列', icon: '⇅' },
  { id: 'array', name: '数组与矩阵', icon: '▦' },
  { id: 'string', name: '串', icon: 'Aa' },
  { id: 'tree', name: '树结构', icon: '⌘' },
  { id: 'graph', name: '图结构', icon: '◌' },
  { id: 'search', name: '查找', icon: '⌕' },
  { id: 'sort', name: '排序', icon: '≋' },
];

window.ALGORA_MODULES = [
  { id:'sequence-list', category:'list', title:'顺序表 · 数组', type:'array', demo:'sequence', time:'访问 O(1) / 插删 O(n)', space:'O(n)', tags:['线性表','数组','随机访问'], summary:'使用连续存储空间保存线性表元素，重点观察插入和删除时的数据移动。' },
  { id:'singly-list-no-head', category:'list', title:'单链表 · 无头结点', type:'linked', demo:'linked', time:'查找 O(n) / 局部插删 O(1)', space:'O(n)', tags:['链表','指针'], summary:'首元结点直接保存数据，空表由空指针表示。' },
  { id:'singly-list-head', category:'list', title:'单链表 · 带头结点', type:'linked', demo:'linked-head', time:'查找 O(n) / 局部插删 O(1)', space:'O(n)', tags:['链表','头结点'], summary:'增加不存放有效数据的头结点，统一空表与非空表操作。' },
  { id:'doubly-list-no-head', category:'list', title:'双链表 · 无头结点', type:'linked', demo:'doubly', time:'查找 O(n) / 局部插删 O(1)', space:'O(n)', tags:['双向链表'], summary:'每个结点同时保存前驱和后继指针，可双向遍历。' },
  { id:'doubly-list-head', category:'list', title:'双链表 · 带头结点', type:'linked', demo:'doubly-head', time:'查找 O(n) / 局部插删 O(1)', space:'O(n)', tags:['双向链表','头结点'], summary:'通过头结点简化双链表边界处理。' },
  { id:'circular-singly-list', category:'list', title:'循环单链表', type:'linked', demo:'circular-singly', time:'查找 O(n)', space:'O(n)', tags:['循环链表'], summary:'尾结点的 next 指回首结点，适合循环访问。' },
  { id:'circular-doubly-list', category:'list', title:'循环双链表', type:'linked', demo:'circular-doubly', time:'查找 O(n)', space:'O(n)', tags:['循环链表','双向'], summary:'头尾双向相连，插删边界统一。' },
  { id:'static-list', category:'list', title:'静态链表', type:'array', demo:'static-list', time:'查找 O(n)', space:'O(n)', tags:['数组','游标'], summary:'用数组下标模拟指针，适用于不支持指针或固定空间场景。' },

  { id:'array-stack', category:'stack-queue', title:'栈 · 顺序存储', type:'stack', demo:'stack', time:'入栈/出栈 O(1)', space:'O(n)', tags:['LIFO','栈'], summary:'只允许在栈顶进行插入和删除，遵循后进先出。' },
  { id:'linked-stack-head', category:'stack-queue', title:'栈 · 链表带头结点', type:'stack', demo:'linked-stack', time:'入栈/出栈 O(1)', space:'O(n)', tags:['栈','链表'], summary:'使用链表头部作为栈顶，动态扩展容量。' },
  { id:'linked-stack-no-head', category:'stack-queue', title:'栈 · 链表无头结点', type:'stack', demo:'linked-stack', time:'入栈/出栈 O(1)', space:'O(n)', tags:['栈','链表'], summary:'栈顶指针直接指向首元结点。' },
  { id:'array-queue', category:'stack-queue', title:'队列 · 顺序存储', type:'queue', demo:'queue', time:'入队 O(1) / 出队 O(n)', space:'O(n)', tags:['FIFO','队列'], summary:'队尾插入、队头删除；普通顺序队列可能产生假溢出。' },
  { id:'linked-queue-head', category:'stack-queue', title:'队列 · 链表带头结点', type:'queue', demo:'linked-queue', time:'入队/出队 O(1)', space:'O(n)', tags:['队列','链表'], summary:'使用 front、rear 指针管理队头与队尾。' },
  { id:'linked-queue-no-head', category:'stack-queue', title:'队列 · 链表无头结点', type:'queue', demo:'linked-queue', time:'入队/出队 O(1)', space:'O(n)', tags:['队列','链表'], summary:'空队列需同时维护 front 与 rear 的空状态。' },
  { id:'circular-queue', category:'stack-queue', title:'循环队列', type:'queue', demo:'circular-queue', time:'入队/出队 O(1)', space:'O(n)', tags:['循环队列'], summary:'通过模运算复用数组空间，并用空位或计数区分队空与队满。' },
  { id:'bracket-match', category:'stack-queue', title:'括号匹配', type:'stack', demo:'bracket', time:'O(n)', space:'O(n)', tags:['栈','应用'], summary:'左括号入栈，右括号与栈顶配对。' },
  { id:'expression-eval', category:'stack-queue', title:'表达式计算', type:'stack', demo:'expression', time:'O(n)', space:'O(n)', tags:['栈','表达式'], summary:'利用操作数栈和运算符栈完成中缀表达式求值。' },
  { id:'deque', category:'stack-queue', title:'双端队列', type:'queue', demo:'deque', time:'两端操作 O(1)', space:'O(n)', tags:['Deque'], summary:'允许在队头和队尾两端插入或删除。' },
  { id:'level-order', category:'stack-queue', title:'队列 · 层次遍历', type:'tree', demo:'level-order', time:'O(n)', space:'O(n)', tags:['队列','二叉树'], summary:'使用队列按层访问树结点。' },

  { id:'array-storage', category:'array', title:'数组存储结构', type:'matrix', demo:'array-storage', time:'访问 O(1)', space:'O(n)', tags:['数组','地址计算'], summary:'理解多维数组按行优先存储时的地址映射。' },
  { id:'symmetric-matrix', category:'array', title:'压缩存储 · 对称矩阵', type:'matrix', demo:'symmetric', time:'访问 O(1)', space:'O(n²/2)', tags:['矩阵','压缩'], summary:'只保存上三角或下三角元素，利用对称性恢复另一半。' },
  { id:'triangular-matrix', category:'array', title:'压缩存储 · 三角矩阵', type:'matrix', demo:'triangular', time:'访问 O(1)', space:'O(n²/2)', tags:['矩阵','压缩'], summary:'只保存有效三角区域与一个公共常量。' },
  { id:'tridiagonal-matrix', category:'array', title:'压缩存储 · 三对角矩阵', type:'matrix', demo:'tridiagonal', time:'访问 O(1)', space:'O(n)', tags:['矩阵','压缩'], summary:'仅存储主对角线及其上下相邻两条对角线。' },
  { id:'sparse-triple', category:'array', title:'稀疏矩阵 · 三元组', type:'matrix', demo:'sparse', time:'遍历 O(t)', space:'O(t)', tags:['稀疏矩阵'], summary:'用 (行, 列, 值) 三元组保存非零元素。' },

  { id:'naive-match', category:'string', title:'朴素模式匹配', type:'string', demo:'naive-match', time:'最坏 O(nm)', space:'O(1)', tags:['字符串','匹配'], summary:'主串与模式串逐位对齐并逐字符比较，失配后右移一位。' },
  { id:'kmp', category:'string', title:'KMP 算法', type:'string', demo:'kmp', time:'O(n+m)', space:'O(m)', tags:['字符串','next数组'], summary:'利用模式串自身的前后缀信息避免主串指针回退。' },

  { id:'binary-tree', category:'tree', title:'二叉树 · 链式存储', type:'tree', demo:'binary-tree', time:'遍历 O(n)', space:'O(h)', tags:['二叉树','遍历'], summary:'观察先序、中序、后序遍历及递归调用次序。' },
  { id:'bst', category:'tree', title:'二叉排序树', type:'tree', demo:'bst', time:'平均 O(log n) / 最坏 O(n)', space:'O(n)', tags:['BST','查找'], summary:'左子树键值更小，右子树键值更大。' },
  { id:'huffman', category:'tree', title:'哈夫曼树', type:'tree', demo:'huffman', time:'O(n log n)', space:'O(n)', tags:['贪心','编码'], summary:'反复合并权值最小的两棵树，构造最优前缀编码。' },
  { id:'threaded-tree', category:'tree', title:'线索二叉树', type:'tree', demo:'threaded', time:'线性遍历 O(n)', space:'O(1) 额外', tags:['线索化'], summary:'利用空指针域保存遍历前驱或后继，减少栈与递归开销。' },
  { id:'avl', category:'tree', title:'AVL 平衡二叉树', type:'tree', demo:'avl', time:'O(log n)', space:'O(n)', tags:['AVL','旋转'], summary:'通过 LL、RR、LR、RL 旋转维持结点平衡因子。' },

  { id:'adjacency-matrix', category:'graph', title:'图 · 邻接矩阵', type:'graph', demo:'adj-matrix', time:'查边 O(1)', space:'O(V²)', tags:['图','存储'], summary:'用二维矩阵表示顶点之间是否存在边及其权值。' },
  { id:'adjacency-list', category:'graph', title:'图 · 邻接表', type:'graph', demo:'adj-list', time:'遍历邻边 O(deg(v))', space:'O(V+E)', tags:['图','存储'], summary:'每个顶点保存一条邻接边链表，更适合稀疏图。' },
  { id:'bfs', category:'graph', title:'广度优先搜索 BFS', type:'graph', demo:'bfs', time:'O(V+E)', space:'O(V)', tags:['图','队列'], summary:'从起点开始按层扩展未访问邻点。' },
  { id:'dfs', category:'graph', title:'深度优先搜索 DFS', type:'graph', demo:'dfs', time:'O(V+E)', space:'O(V)', tags:['图','递归'], summary:'沿一条路径尽可能深入，再回溯探索其他分支。' },
  { id:'prim', category:'graph', title:'Prim 最小生成树', type:'graph', demo:'prim', time:'O(V²) 或 O(E log V)', space:'O(V)', tags:['MST','贪心'], summary:'从已有生成树向外选择权值最小的跨集合边。' },
  { id:'kruskal', category:'graph', title:'Kruskal 最小生成树', type:'graph', demo:'kruskal', time:'O(E log E)', space:'O(V)', tags:['MST','并查集'], summary:'按边权从小到大选择不会形成环的边。' },
  { id:'dijkstra', category:'graph', title:'Dijkstra 最短路径', type:'graph', demo:'dijkstra', time:'O(E log V)', space:'O(V)', tags:['最短路','贪心'], summary:'反复确定当前距离最小的未确定顶点，不适用于负权边。' },
  { id:'floyd', category:'graph', title:'Floyd 全源最短路径', type:'matrix', demo:'floyd', time:'O(V³)', space:'O(V²)', tags:['最短路','动态规划'], summary:'逐个允许中间顶点参与，更新任意两点间最短距离。' },
  { id:'bellman-ford', category:'graph', title:'Bellman–Ford', type:'graph', demo:'bellman', time:'O(VE)', space:'O(V)', tags:['最短路','负权'], summary:'对所有边重复松弛，可检测可达负权环。' },
  { id:'topological-sort', category:'graph', title:'拓扑排序', type:'graph', demo:'topological', time:'O(V+E)', space:'O(V)', tags:['DAG','栈/队列'], summary:'不断输出入度为零的顶点，得到偏序关系的线性序列。' },
  { id:'critical-path', category:'graph', title:'关键路径', type:'graph', demo:'critical-path', time:'O(V+E)', space:'O(V)', tags:['AOE网','项目管理'], summary:'计算事件最早与最迟发生时间，找出零时差活动。' },

  { id:'linear-search-unsorted', category:'search', title:'顺序查找 · 无序表', type:'array', demo:'linear-search', time:'O(n)', space:'O(1)', tags:['查找'], summary:'从头到尾依次比较，适用于无序或规模较小的数据。' },
  { id:'linear-search-sorted', category:'search', title:'顺序查找 · 有序表', type:'array', demo:'ordered-linear-search', time:'O(n)', space:'O(1)', tags:['查找','有序表'], summary:'利用有序性在当前元素超过目标时提前停止。' },
  { id:'binary-search', category:'search', title:'折半查找', type:'array', demo:'binary-search', time:'O(log n)', space:'O(1)', tags:['查找','分治'], summary:'在有序表中反复舍弃一半搜索区间。' },
  { id:'red-black-tree', category:'search', title:'红黑树', type:'tree', demo:'red-black', time:'O(log n)', space:'O(n)', tags:['平衡树'], summary:'通过颜色约束与旋转保证从根到叶路径长度近似平衡。' },
  { id:'b-tree', category:'search', title:'B 树', type:'tree', demo:'b-tree', time:'O(logₘ n)', space:'O(n)', tags:['多路查找树','数据库'], summary:'每个结点保存多个关键字，降低外存访问层数。' },
  { id:'hash-chaining', category:'search', title:'哈希表 · 拉链法', type:'hash', demo:'hash-chain', time:'平均 O(1)', space:'O(n)', tags:['哈希','冲突'], summary:'冲突元素存入同一桶的链表。' },
  { id:'hash-open', category:'search', title:'哈希表 · 开放定址', type:'hash', demo:'hash-open', time:'平均 O(1)', space:'O(m)', tags:['哈希','线性探测'], summary:'冲突后按探测序列寻找下一个空位置。' },

  { id:'insertion-sort', category:'sort', title:'直接插入排序', type:'bars', demo:'insertion-sort', time:'O(n²)', space:'O(1)', tags:['排序','稳定'], summary:'维护已排序区间，将当前元素插入合适位置。' },
  { id:'binary-insertion-sort', category:'sort', title:'折半插入排序', type:'bars', demo:'binary-insertion-sort', time:'O(n²)', space:'O(1)', tags:['排序','稳定'], summary:'用折半查找确定插入位置，但元素移动量仍为 O(n²)。' },
  { id:'shell-sort', category:'sort', title:'希尔排序', type:'bars', demo:'shell-sort', time:'依赖增量序列', space:'O(1)', tags:['排序','不稳定'], summary:'按逐渐缩小的增量分组执行插入排序。' },
  { id:'bubble-sort', category:'sort', title:'冒泡排序', type:'bars', demo:'bubble-sort', time:'O(n²)', space:'O(1)', tags:['排序','稳定'], summary:'相邻元素逆序时交换，每轮将最大元素推向末端。' },
  { id:'quick-sort', category:'sort', title:'快速排序', type:'bars', demo:'quick-sort', time:'平均 O(n log n)', space:'平均 O(log n)', tags:['排序','分治'], summary:'选取枢轴完成一次划分，再递归排序左右区间。' },
  { id:'selection-sort', category:'sort', title:'简单选择排序', type:'bars', demo:'selection-sort', time:'O(n²)', space:'O(1)', tags:['排序','不稳定'], summary:'每轮从未排序区间选择最小元素放到前端。' },
  { id:'heap-sort', category:'sort', title:'堆排序', type:'bars', demo:'heap-sort', time:'O(n log n)', space:'O(1)', tags:['排序','堆'], summary:'建立大根堆，反复交换堆顶与末尾并调整。' },
  { id:'merge-sort', category:'sort', title:'归并排序', type:'bars', demo:'merge-sort', time:'O(n log n)', space:'O(n)', tags:['排序','稳定'], summary:'递归分解序列，再合并两个有序子序列。' },
  { id:'radix-sort', category:'sort', title:'基数排序', type:'bars', demo:'radix-sort', time:'O(d(n+r))', space:'O(n+r)', tags:['排序','稳定'], summary:'按个位、十位等关键字依次进行稳定分配与收集。' },
];
